Models/Film.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Film_Version_2.Models
{
    public class Film
    {
        
            
            public int Id { get; set; }
        [Required(ErrorMessage = "Поле должно быть установлено")]    
        [DisplayName("Название")]
        
            public string? Name { get; set; }
        [Required(ErrorMessage = "Поле должно быть установлено")]
        [DisplayName("Описание")]
            public string? Description { get; set; }
        [Required(ErrorMessage = "Поле должно быть установлено")]
        [DisplayName("Жанр")]
            public string? Jenre { get; set; }
        [Required(ErrorMessage = "Поле должно быть установлено")]
        [DisplayName("Год")]
        [Range(1985,2024, ErrorMessage ="Недопустимый год")]
            public int Year { get; set; }
        [Required(ErrorMessage = "Поле должно быть установлено")]
        [DisplayName("Режиссёр")]
            public string? Producer { get; set; }
        [Required(ErrorMessage = "Поле должно быть установлено")]
        [DisplayName("Постер")]
            public string? Poster { get; set; }
        
    }
}

Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Film_Version_2.Models;
using System.IO;

namespace Film_Version_2.Controllers
{
    public class FilmsController : Controller
    {
        private readonly FilmContext _context;
        IWebHostEnvironment _appEnvironment;  // нужем нам для того , чтобы сохранять и доставать картинки из папки files 
        public FilmsController(FilmContext context, IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _appEnvironment = appEnvironment;
        }

        // GET: Films
        public async Task<IActionResult> Index()
        {
            return View(await _context.Films.ToListAsync());
        }

        // GET: Films/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Films
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // GET: Films/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: Films/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Jenre,Year,Producer,Poster")] Film film , IFormFile uploadedFile)
        {

           var names =  _context.Films.Select(m => m.Name);

            if(names.Contains(film.Name))
            {
                ModelState.AddModelError("Name", "Такое название уже существует");
            }
            if (ModelState.IsValid)
            {
                
                _context.Add(film);
                if (uploadedFile != null)
                {
                    string path = "/Files/" + uploadedFile.FileName;

                    using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                    {
                        await uploadedFile.CopyToAsync(fileStream);
                        film.Poster = path;
                    }
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            

            return View(film);


        }

        // GET: Films/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
      
            if (id == null)
            {
                return NotFound();
            }
            var film = await _context.Films.FindAsync(id);


            if (film == null)
            {
                return NotFound();
            }
           
            return View(film);
        }

        // POST: Films/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Jenre,Year,Producer,Poster")] Film film , IFormFile uploadedFile)
        {
            if (id != film.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    
                    if (uploadedFile != null)
                    {
                        string path = "/Files/" + uploadedFile.FileName;

                        using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                        {
                            await uploadedFile.CopyToAsync(fileStream);
                            film.Poster = path;
                        }
                    }
                    _context.Update(film);
                    await _context.SaveChangesAsync();
                   
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmExists(film.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }

        // GET: Films/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Films
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var film = await _context.Films.FindAsync(id);
            if (film != null)
            {
                _context.Films.Remove(film);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmExists(int id)
        {
            return _context.Films.Any(e => e.Id == id);
        }

      


    }
}

Views/Films/Create.cshtml
@model Film_Version_2.Models.Film

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h4>Добавление нового фильма</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" asp-controller="Films" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Jenre" class="control-label"></label>
                <input asp-for="Jenre" class="form-control" />
                <span asp-validation-for="Jenre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producer" class="control-label"></label>
                <input asp-for="Producer" class="form-control" />
                <span asp-validation-for="Producer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poster" class="control-label"></label>
                <input asp-for="Poster" class="form-control" type="file" name="uploadedFile"/><br>
                <input asp-for="Poster" class="form-control" type="submit" value="Загрузить"  />
                
            </div>
            <div class="btn_helpers_Index_Cre_del_edit">
                <br />
                <a asp-action="Index" style="text-decoration:none"><i>Вернуться на главную страницу</i></a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Films/Delete.cshtml
@model Film_Version_2.Models.Film

@{
    ViewData["Title"] = "Удаление";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h3>Вы действительно хотите удалить этот фильм?</h3>
<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Jenre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Jenre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Producer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Producer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poster)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.Poster" style="max-width: 200px ; max-height: 2500px;"/>
        </dd>
        <dt>
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Удалить" class="btn btn-danger" />
                <a asp-action="Index" style="text-decoration:none">Вернуться на главную</a>
            </form>
        </dt>
        
    </dl>

</div>

Views/Films/Details.cshtml
@model Film_Version_2.Models.Film

@{
    ViewData["Title"] = "Подробности";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div>
    <h4>Полное описание фильма</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Jenre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Jenre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Producer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Producer)
        </dd>
        <dd>    <img src="@Model.Poster" style="max-width: 60% ; max-height:660px; " /></dd>


        <dt>
            <a asp-action="Edit" asp-route-id="@Model?.Id" style="text-decoration: none">Редактирование</a>
           
        </dt>
        <dt>
            <a asp-action="Index" style="text-decoration: none">Вернуться на главную</a>
        </dt>
    </dl>
  
</div>

Views/Films/Edit.cshtml
@model Film_Version_2.Models.Film

@{
    ViewData["Title"] = "Редактирование";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="changes">
    <h4>Изменение</h4>
    <div class="row" style=" display: flex; margin-top:5%">
    <div class="col-md-4" >
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Jenre" class="control-label"></label>
                <input asp-for="Jenre" class="form-control" />
                <span asp-validation-for="Jenre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producer" class="control-label"></label>
                <input asp-for="Producer" class="form-control" />
                <span asp-validation-for="Producer" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <label asp-for="Poster" class="control-label"></label>
                <input asp-for="Poster" class="form-control" type="file" name="uploadedFile" />
               
                
                <br />
                <input asp-for="Poster" class="form-control" type="submit" value="Загрузить" />
            </div>
            <div>
                <a asp-action="Index" style="text-decoration:none">Вернуться на главную</a>
            </div>
        </form>
    </div>
    <img src="@Model.Poster" style="max-width: 60% ; max-height:660px; />
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Films/Index.cshtml
@model IEnumerable<Film_Version_2.Models.Film>  //по какой модели типизируетя вьюшка. В этом случае - films

@{
    ViewData["Title"] = "Главная";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 style="text-align: center">Топ 10 фильмов , рекомендуемых Люмьер</h1>

<p class="btn_helper_CreateNew">
    <a asp-action="Create">Создать новый</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Jenre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poster)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Jenre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Producer)
            </td>
            <td>
               <img src="@item.Poster" style="width:128px;height:128px;"  />
            </td>
            <td class="btn_helpers_Index_Cre_del_edit">
                <a asp-action="Edit" asp-route-id="@item.Id" style="text-decoration:none"><i>Изменить</i></a>
                    <a asp-action="Details" asp-route-id="@item.Id" style="text-decoration:none"><i>Подробности</i></a>
                    <a asp-action="Delete" asp-route-id="@item.Id" style="text-decoration:none"><i>Удалить</i></a>
            </td>
        </tr>
}
    </tbody>
</table>